version: "3.8"

services:
  aws:
    image: localstack/localstack:latest
    container_name: aws
    ports:
      - '4566:4566'
      - '${PORT_WEB_UI-9081}:${PORT_WEB_UI-8080}'
    environment:
      - EDGE_PORT=4566
      - SERVICES=sqs,s3,ses,sns
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - '/tmp/localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
    healthcheck:
      test:
        - CMD
        - bash
        - -c
        - awslocal sqs list-queues && awslocal ses list-identities && awslocal s3 ls && awslocal sns list-topics
      interval: 5s
      timeout: 10s
      start_period: 10s
    networks:
      local:
        aliases:
          - aws
  snowflakerepro:
    container_name: "snowflakerepro"
    image: localstack/snowflake:latest@sha256:45a6a372d8a8cd58186f05f1ea8acbf3973df104cb38c14063e3d66e8cc79509
    networks:
      local:
        aliases:
          - snowflake.localhost.localstack.cloud
    ports:
      - "4567:4567"
      - "4510-4559:4510-4559"
      - "443:443"
    environment:
      - GATEWAY_LISTEN=0.0.0.0:4567
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN:?}
      - DOCKER_FLAGS='-e SF_LOG=trace'
      - DEBUG=1
      - IMAGE_NAME=localstack/snowflake
      - SF_S3_ENDPOINT=aws:4566
      - SF_S3_ENDPOINT_EXTERNAL=s3.localhost.localstack.cloud:4566
    volumes:
      - "./volume:/var/lib/localstack"
networks:
  local:
    external: true
