version: "3.8"

services:
  snowflake_repro:
    container_name: "snowflake_repro"
    image: localstack/snowflake:latest@sha256:86e410496a1e0912fe5376520f95f970c792559c821c460d935e6e9eb547e37d
    networks:
      local:
        aliases:
          - snowflake.localhost.localstack.cloud
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
      - "127.0.0.1:443:443"
    environment:
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN:?}
      - DOCKER_FLAGS='-e SF_LOG=trace'
      - DEBUG=1
      - IMAGE_NAME=localstack/snowflake
    volumes:
      - "./volume:/var/lib/localstack"
networks:
  local:
    external: true
