CREATE TABLE IF NOT EXISTS TEST.PUBLIC.MYTABLE (
    ID VARCHAR(255) PRIMARY KEY,
    NAME NUMBER(38,17) NOT NULL
);

CREATE STAGE IF NOT EXISTS TEST.PUBLIC.MYSTAGE;

CREATE OR REPLACE FILE FORMAT TEST.PUBLIC.MYFORMAT
    TYPE = 'CSV'
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"';